name: publish container image
on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read
jobs:
  build:
    name: Build and Publish image
    strategy:
      fail-fast: true
      matrix:
        runs-on:
          - "ubuntu-latest"
          - "buildjet-2vcpu-ubuntu-2204-arm"
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "azuki-bar"
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare-tag
        id: tags
        run: |
          arch=""
          # https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context
          case "${{ runner.arch }}" in
            "X64" ) arch="amd64" ;;
            "ARM64" ) arch="arm64" ;;
          esac

          echo "tag=${{ github.sha }}-${arch}" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/azuki-bar/hello-buildjet-nextjs:${{ steps.tags.outputs.tag }}

  merge-images:
    runs-on: "ubuntu-latest"
    needs: ["build"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "azuki-bar"
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a New Image
        run: |
          image_tag="ghcr.io/azuki-bar/hello-buildjet-nextjs:${{ github.sha }}"
          docker buildx imagetools create --dry-run \
            -tag ${image_tag} \
            ${image_tag}-arm64 \
            ${image_tag}-amd64

          docker buildx imagetools create \
            --tag ${image_tag} \
            ${image_tag}-arm64 \
            ${image_tag}-amd64

      - name: Check New Manifests
        run: |
          # 表示用
          docker buildx imagetools inspect

          docker buildx imagetools inspect \
            ghcr.io/azuki-bar/hello-buildjet-nextjs:${{ github.sha }} \
            --format "{{json .Image}}" \
          | jq -e '. | keys | contains(["linux/amd64", "linux/arm64"])'

  build-with-qemu:
    name: Build and Publish image with QEMU
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "azuki-bar"
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/azuki-bar/hello-buildjet-nextjs:${{ github.sha }}-qemu
          platforms: linux/amd64,linux/arm64
